name: Docker Image CI

on:
  push:
    branches: [ dev, staging, main ]
  pull_request:
    branches: [ dev, staging, main ]

jobs:

  build-developement:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --target development --file Dockerfile --tag suitntie-web-v2-api:development$(date +%s)

  build-staging:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --target staging --file Dockerfile --tag suitntie-web-v2-api:staging$(date +%s)
      
  build-production:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --target production --file Dockerfile --tag suitntie-web-v2-api:production$(date +%s)
