name: Source Code Check
on:
  push:
    branches: [dev, staging, main]
  pull_request:
    branches: [dev, staging, main]
jobs:
  prettier-lint:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format-check
      # - name: Lint
      #   run: npm run lint
